name: CI/CD Workflow

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        python manage.py test

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set environment variables
      run: |
        echo "PYTHONANYWHERE_HOST=$(grep -oP 'PYTHONANYWHERE_HOST=\K.*' .env)" >> $GITHUB_ENV
        echo "PYTHONANYWHERE_USERNAME=$(grep -oP 'PYTHONANYWHERE_USERNAME=\K.*' .env)" >> $GITHUB_ENV
        echo "PYTHONANYWHERE_PASSWORD=$(grep -oP 'PYTHONANYWHERE_PASSWORD=\K.*' .env)" >> $GITHUB_ENV

    - name: Deploy to PythonAnywhere
      uses: appleboy/ssh-action@master
      with:
        host: ${{ env.PYTHONANYWHERE_HOST }}
        username: ${{ env.PYTHONANYWHERE_USERNAME }}
        password: ${{ env.PYTHONANYWHERE_PASSWORD }}
        script: |
          cd /home/sgjustino/redditproject
          git pull
          source myvirtualenv/bin/activate
          pip install -r requirements.txt
          python manage.py migrate
          touch /var/www/sgjustino_pythonanywhere_com_wsgi.py
